### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by imiskolee** [cymheart/tau#1]
Hi:
   我们正在研发一款跨平台的商业DAW软件，不知道是否有兴趣细聊。 微信: miskolee

**Comment by cymheart** [comment]
Hi，我目前是在个人开发完善这个DAW方向的核心库。。

**Comment by cymheart** [comment]
> Hi: 我们正在研发一款跨平台的商业DAW软件，不知道是否有兴趣细聊。 微信: miskolee

**Comment by cymheart** [comment]
Hi，我目前是在个人开发完善这个DAW方向的核心库。。
